language: python
dist: jammy

matrix:
  include:
    - python: 3.8
      env:
        - TOX_ENV=py38
    - python: 3.10
      env:
        - TOX_ENV=py310
    - python: 3.12
      env:
        - TOX_ENV=py312
    - python: 3.10
      env:
        - TOX_ENV=pep8

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
